//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallStatus
    {
        public int id { get; set; }
        public Nullable<int> MadadkarId { get; set; }
        public string MaadadkarName { get; set; }
        public Nullable<int> HamiId { get; set; }
        public string HamiName { get; set; }
        public string PhoneNumber { get; set; }
        public string Date { get; set; }
        public string StartTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
        public string EndTime { get; set; }
    }
}
