//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FG_HamiMadadkarsInfo
    {
        public int HamiMadadkarId { get; set; }
        public Nullable<int> HamiId { get; set; }
        public Nullable<int> MadadkarId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> MadadkarCode { get; set; }
        public string MadadkarLName { get; set; }
        public string MadadkarFName { get; set; }
        public string MadadkarPhone { get; set; }
        public string MadadkarMobile { get; set; }
        public string MadadkarMobile2 { get; set; }
        public string HamiCode { get; set; }
        public string HamiLName { get; set; }
        public string HamiFName { get; set; }
        public string HamiMobile1 { get; set; }
        public string HamiMobile2 { get; set; }
    }
}
