//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FG_Hamis
    {
        public int HamiId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<bool> HamiConfirm { get; set; }
        public string HamiCode { get; set; }
        public string HamiFName { get; set; }
        public string HamiLName { get; set; }
        public string HamiMobile1 { get; set; }
        public string HamiMobile2 { get; set; }
        public string HamiPhone1 { get; set; }
        public string HamiPhone2 { get; set; }
        public string HamiBirthdate { get; set; }
        public Nullable<int> HamiJobId { get; set; }
        public string HamiEmail { get; set; }
        public string HamiAddress { get; set; }
        public Nullable<System.DateTime> HamiLastAction { get; set; }
        public Nullable<int> HamiPrice { get; set; }
        public string HamiJobStatus { get; set; }
        public string HamiUID { get; set; }
        public string HamiPass { get; set; }
        public string HamiComment { get; set; }
        public string HamiAllPhones { get; set; }
        public Nullable<int> PersonnelId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> HamiMadadkar { get; set; }
        public string HamiKey { get; set; }
        public string HamiPassword { get; set; }
        public string Hamistartdate { get; set; }
    }
}
