//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FG_HamiMadadjusInfo
    {
        public int HamiMadadjuId { get; set; }
        public Nullable<int> HamiId { get; set; }
        public Nullable<int> MadadjuId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string HamiFName { get; set; }
        public string HamiLName { get; set; }
        public string HamiName { get; set; }
        public string HamiPhone1 { get; set; }
        public string MadadjuFName { get; set; }
        public string MadadjuLName { get; set; }
        public string MadadJuName { get; set; }
        public Nullable<int> MadadjuCode { get; set; }
        public string MadadjuPhone { get; set; }
        public string MadadjuMobile { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
    }
}
