//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FG_Madadkars
    {
        public int MadadkarId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<bool> MadadkarActive { get; set; }
        public Nullable<int> MadadkarCode { get; set; }
        public Nullable<bool> MadadkarConfirm { get; set; }
        public string MadadkarFName { get; set; }
        public string MadadkarLName { get; set; }
        public string MadadkarFathername { get; set; }
        public string MadadkarShenasnameh { get; set; }
        public string MadadkarMelli { get; set; }
        public string MadadkarPersonnel { get; set; }
        public string MadadkarBirhtdate { get; set; }
        public string MadadkarBirthplace { get; set; }
        public string MadadkarMazhab { get; set; }
        public Nullable<int> MadadkarSex { get; set; }
        public Nullable<byte> MadadkarMarridId { get; set; }
        public Nullable<int> MadadkarLevel { get; set; }
        public string MadadkarEducation { get; set; }
        public Nullable<byte> MadadkarSarbazi { get; set; }
        public string MadadkarJob { get; set; }
        public string MadadkarPhone { get; set; }
        public string MadadkarMobile { get; set; }
        public string MadadkarMobile2 { get; set; }
        public string MadadkarAccount { get; set; }
        public string MadadkarAddress { get; set; }
        public string MadadkarEmail { get; set; }
        public string MadadkarImg { get; set; }
        public Nullable<System.DateTime> MadadKarLastAction { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> PersonnelId { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
