//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public string UniqueId { get; set; }
        public string RefNumber { get; set; }
        public string ResNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> SettleDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public string CardNumber { get; set; }
        public string SecurePan { get; set; }
        public string TraceNo { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string State { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Verified { get; set; }
    }
}
