//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneChange
    {
        public int id { get; set; }
        public Nullable<int> MadadkarId { get; set; }
        public string MadadkarName { get; set; }
        public Nullable<int> HamiId { get; set; }
        public string HamiName { get; set; }
        public string OldPhoneNumber { get; set; }
        public string NewPhoneNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public string Description { get; set; }
    }
}
