//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftPersons
    {
        public int id { get; set; }
        public int ShiftId { get; set; }
        public int MadadkarId { get; set; }
        public string MadadkarName { get; set; }
        public Nullable<System.TimeSpan> EnterTime { get; set; }
        public Nullable<System.TimeSpan> ExitTime { get; set; }
    
        public virtual JobShift JobShift { get; set; }
    }
}
