//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPExtensions
    {
        public int Id { get; set; }
        public Nullable<int> Extention { get; set; }
        public string DisplayName { get; set; }
        public string Password { get; set; }
        public Nullable<int> MadadkarId { get; set; }
        public string MadadkarName { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
