//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccessInfo
    {
        public int UserAccessId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public int ObjectId { get; set; }
        public Nullable<bool> CanView { get; set; }
        public Nullable<bool> CanInsert { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanPrint { get; set; }
        public string ObjectTitle { get; set; }
        public string ObjectName { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
