//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenusInfo
    {
        public int UserMenuId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<short> MenuType { get; set; }
        public string MenuCaption { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public string ObjectName { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string MenuValue { get; set; }
        public string MenuImage { get; set; }
        public string MenuDesc { get; set; }
    }
}
