//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRules
    {
        public int UserRuleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ObjectRuleId { get; set; }
        public Nullable<bool> CanUse { get; set; }
        public Nullable<int> ProgramId { get; set; }
    }
}
