//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Payments
    {
        public string UniqeId { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> HamiId { get; set; }
        public string HamiName { get; set; }
        public Nullable<int> MadadkarId { get; set; }
        public string MadadkarName { get; set; }
        public string RefNumber { get; set; }
        public string ResNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> SettleDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public string CardNumber { get; set; }
        public string SecurePan { get; set; }
        public string TraceNo { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string State { get; set; }
        public Nullable<int> MadadjouId { get; set; }
        public string MadadjouName { get; set; }
        public Nullable<int> DonationAmount { get; set; }
        public Nullable<int> OptionalDonation { get; set; }
        public string OptionalDescription { get; set; }
    }
}
